networks:
  backend:
    driver: bridge

services:

  traefik:
    restart: unless-stopped
    image: "traefik:v2.10"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=akkadius1+certbot@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${IP_ADDRESS}:80:80"
      - "${IP_ADDRESS}:443:443"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend

  kuma:
    restart: unless-stopped
    image: louislam/uptime-kuma:2.0.0-beta-slim.1
    environment:
      - TZ=${TZ:-US/Central}
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=mariadb
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=${MARIADB_DATABASE}
      - UPTIME_KUMA_DB_USERNAME=${MARIADB_USER}
      - UPTIME_KUMA_DB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.status-http.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.status-http.entrypoints=web"
      - "traefik.http.routers.status-http.service=status-http"
      - "traefik.http.services.status-http.loadbalancer.server.port=3001"
      - "traefik.http.routers.status-http.middlewares=status-https"
      - "traefik.http.middlewares.status-https.redirectscheme.scheme=https"
      # https
      - "traefik.http.routers.status-https.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.status-https.entrypoints=websecure"
      - "traefik.http.routers.status-https.tls.certresolver=le"
      - "traefik.http.routers.status-https.service=status-https"
      - "traefik.http.services.status-https.loadbalancer.server.port=3001"


  mariadb:
    restart: unless-stopped
    build:
      context: ./containers/mariadb
      args:
        - INNODB_BUFFER_POOL_SIZE=${INNODB_BUFFER_POOL_SIZE:-256MB}
    ports:
      - ${IP_ADDRESS}:3306:3306
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=NO
      - TZ=${TZ:-US/Central}
    networks:
      - backend