networks:
  backend:
    driver: bridge

services:

  kuma:
    restart: unless-stopped
    image: louislam/uptime-kuma:2.0.0-beta-slim.1
    ports:
      - ${IP_ADDRESS}:3001:3001
    environment:
      - TZ=${TZ:-US/Central}
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=mariadb
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=${MARIADB_DATABASE}
      - UPTIME_KUMA_DB_USERNAME=${MARIADB_USER}
      - UPTIME_KUMA_DB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - backend

  mariadb:
    restart: unless-stopped
    build:
      context: ./containers/mariadb
      args:
        - INNODB_BUFFER_POOL_SIZE=${INNODB_BUFFER_POOL_SIZE:-256MB}
    ports:
      - ${IP_ADDRESS}:3306:3306
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=NO
      - TZ=${TZ:-US/Central}
    networks:
      - backend